# Read the Docs configuration file for Sphinx projects
 5version: 2

 8build:
 9  os: ubuntu-24.04
10  tools:
11    python: "3.12"
12 
17# Build documentation in the "docs/" directory with Sphinx
18sphinx:
19  configuration: docs/conf.py
20  # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
21  # builder: "dirhtml"
22  # Fail on all warnings to avoid broken references
23  # fail_on_warning: true
24
25# Optionally build your docs in additional formats such as PDF and ePub
26# formats:
27#   - pdf
28#   - epub
29
30# Optional but recommended, declare the Python requirements required
31# to build your documentation
32# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
33# python:
34#   install:
35#     - requirements: docs/requirements.txt
